version: "3"
services:
  react:
    container_name: react
    build: ./client

  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=jiechenmc@gmail.com
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
      - react

volumes:
  mydatabase:
  nginx_secrets:


